@startuml Recipe Service. Диаграмма компонентов

' Скины и стили
skinparam componentStyle rectangle
skinparam wrapWidth 250
skinparam packageStyle rectangle
skinparam monochrome true
skinparam defaultFontName Arial

package "Сервис рецептов" {

  ' Компоненты
  component RecipeManager as "Менеджер рецептов" {
    interface "IRecipeCRUD" as RecipeCRUD
  }
  component CommentManager as "Менеджер комментариев" {
    interface "ICommentCRUD" as CommentCRUD
  }
  component SearchEngine as "Поисковый движок" {
    interface "ISearch" as Search
  }
  component NotificationService as "Сервис уведомлений"
  component ImageStorage as "Хранилище изображений" {
    interface "IImageStorage" as ImageStore
  }
  
  ' Взаимодействия
  RecipeCRUD --> CommentManager : "Управление комментариями связанными с рецептом"
  Search --> RecipeManager : "Поиск по рецептам"
  RecipeManager --> ImageStorage : "Загрузка/Получение изображений"
  RecipeManager --> NotificationService : "Уведомления о новых рецептах или изменениях"
  CommentManager --> NotificationService : "Уведомления о новых комментариях"
}

@enduml
